spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-user-service
              uri: http://localhost:8082
              predicates:
                - Path=/user-wallet/**
              filters:
                #                - PrefixPath=/api
                - AddResponseHeader=X-Powered, Nuran Team Gateway Service
                - Retry=20
            - id: ms-transaction-history
              uri: http://localhost:8081
              predicates:
                - Path=/transaction-history/**
              filters:
                #                - PrefixPath=/api
                - AddResponseHeader=X-Powered, Nuran Team Gateway Service



logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG